---
- name: Install Windows Exporter
  hosts: 10.10.5.181  # Replace with the appropriate host/group name from your inventory
  gather_facts: no
  become: yes
  become_method: runas
  tasks:
    - name: Download Windows Exporter zip
      win_get_url:
        url: https://github.com/prometheus-community/windows_exporter.git
        dest: C:\Users\windows_exporter.zip

    - name: Unzip Windows Exporter
      win_shell: Expand-Archive -Path C:\Users\windows_exporter.zip -DestinationPath "C:\Program Files\windows_exporter"

    - name: Start Windows Exporter
      win_shell: Start-Process -FilePath "C:\Program Files\windows_exporter\windows_exporter.exe"
  
