---
- name: Install Windows Exporter
  hosts: 10.10.5.181  # Replace with the appropriate host/group name from your inventory
  gather_facts: no
  tasks:
    - name: Download Windows Exporter zip
      win_get_url:
        url: https://github.com/prometheus-community/windows_exporter/releases/download/v0.16.0/windows_exporter-0.16.0.zip
        dest: C:\\Users\\windows_exporter.zip

    - name: Unzip Windows Exporter
      win_shell: Expand-Archive -Path C:\\Users\\windows_exporter.zip -DestinationPath C:\\Program Files\\windows_exporter
      become: yes

    - name: Start Windows Exporter
      win_service:
        name: windows_exporter
        start_mode: auto
        state: started
