---
- name: Install Windows Exporter
  hosts: 10.10.5.181  # Replace with the appropriate host/group name from your inventory
  gather_facts: yes
  tasks:
    - name: Download Windows Exporter zip
      win_get_url:
        url: https://github.com/prometheus-community/windows_exporter.git
        dest: C:\Users\windows_exporter.zip

    - name: Unzip Windows Exporter
      win_shell: Expand-Archive -Path C:\Users\windows_exporter.zip -DestinationPath "C:\Program Files\windows_exporter"
      become: no
      
    - name: Start Windows Exporter
      win_shell: Start-Process C:\\Program Files\\windows_exporter\\windows_exporter.zip"
      become: no
