---
- name: Copy Executables from Minio
  hosts: 10.10.5.181
  gather_facts: yes

  tasks:
    - name: Copy files using s3_copy module
      community.general.s3_copy:
        source: "s3://arc/Arc_11102023/"
        destination: "C:\\Program Files\\"
        mode: recursive
        validate_certs: no
      become: yes
