---
- hosts: 10.10.5.183
  gather_facts: yes
  tasks:
    - name: Copy file from Unix server to Windows 10 machine
      ansible.windows.win_copy:
        src: /kap-user/test
        dest: C:\Users
      delegate_to: "{{ ansible_ssh_host }}"
      become: yes
      become_user: inndata
  vars:
    ansible_ssh_host: 10.10.5.76
    ansible_ssh_user: inndata
    ansible_ssh_pass: 123!@#
