---
- hosts: 10.10.5.182
  become: no
  environment:
    MINIO_ACCESS_KEY: "JXTFBt1pDco6bUtSukj6"
    MINIO_SECRET_KEY: "QffFMVJyZqiVOhvJFEZZAKWHGCsrvxd6VcKrLVA6"
  tasks:
   - name: Download file from Minio
     win_get_url:
      url: "https://10.10.5.76:9001/security/SQLite/sqlite3.exe"
      dest: C:\\Users\\
      validate_certs: no

