- name: Transfer file from SFTP to Windows
  hosts: 10.10.5.183
  gather_facts: yes
- vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Copy file from SFTP to AWX host
      shell: scp kap-user@10.10.5.76:/kap-user/test /tmp/test
      args:
        executable: /usr/bin/bash

    - name: Copy file to Windows server
      win_copy:
        src: "/tmp/test"
        dest: "C:\\PrometheusExporter\\test"
