---
- name: Copy file from Unix server to Windows 10 machine
  hosts: 10.10.5.183
  gather_facts: no
  vars:
    destination_host: 10.10.5.183
    destination_path: "C:\\PrometheusExporter"
    source_host: 10.10.5.76
    source_username: inndata
    source_password: "123!@#"
    source_path: "/kap-user/"
    source_filename: "test"
  tasks:
    - name: Copy file from Unix server to Windows 10
      ansible.windows.win_copy:
        src: "{{ source_username }}:{{ source_password }}@{{ source_host }}{{ source_path }}{{ source_filename }}"
        dest: "{{ destination_path }}\\{{ source_filename }}"
      delegate_to: unix_server
