---
- name: Copy file from Unix server to Windows server
  hosts: localhost
  gather_facts: yes
  vars:
    source_host: 10.10.5.76
    source_username: inndata
    source_password: "123!@#"
    source_path: "/kap-user/"
    source_filename: "test"
    destination_host: 10.10.5.183
    destination_path: "C:\\PrometheusExporter"

  tasks:
  - name: Copy file from Unix server to Windows
    ansible.windows.win_copy:
      src: "{{ source_path }}{{ source_filename }}"
      dest: "{{ destination_path }}\\{{ source_filename }}"

    become: no
