- name: Transfer file from SFTP to Windows
  hosts: 10.10.5.183
  gather_facts: yes

  tasks:
    - name: Fetch file from SFTP server
      fetch:
        src: "/kap-user/test"  # Adjust this to the correct SFTP path
        dest: "/tmp/test"
        flat: yes
        validate_certs: no
        fail_on_missing: yes

    - name: Copy file to Windows server
      win_copy:
        src: "/tmp/test"
        dest: "C:\\PrometheusExporter\\test"
