---
- name: Transfer file from SFTP to Windows
  hosts: 10.10.5.183
  gather_facts: yes

  tasks:
    - name: Copy file from SFTP to Windows
      win_copy:
        src: "/tmp/"  # Adjust the source path
        dest: "C:\\PrometeusExporter\\test"
      delegate_to: 10.10.5.183
