---
- name: Transfer file from SFTP to Windows
  hosts: 10.10.5.183
  gather_facts: yes

  tasks:
    - name: Copy file from SFTP to Windows
      win_copy:
        src: "sftp://inndata@10.10.5.76/inndata/test"  # Adjust the source path
        dest: "C:\\PrometheusExporter\\test"
      delegate_to: 10.10.5.76
