---
- name: Transfer files from SFTP to Windows
  hosts: 10.10.5.183  # Replace with your target host/group

  tasks:
    - name: Download files from SFTP
      win_shell: |
        psftp.exe kap-user@10.10.5.76 -pw 123!@# -b sftp_commands.txt
      args:
        executable: powershell.exe
      environment:
        PSFTP_PASS: "123!@#"  # Replace with your SFTP password

    - name: Copy files to Windows server
      win_copy:
        src: "C:\\Users\\inndata-dev-003\\Documents"
        dest: "C:\\PrometheusExporter"
