---
- name: Copy file from Linux to Windows
  hosts: 10.10.5.183
  gather_facts: yes

  tasks:
    - name: Copy file from Linux to Windows
      ansible.builtin.copy:
        src: "sftp://inndata@10.10.5.76/inndata/testfile.txt"
        dest: "C:\\PrometheusExporter\\"
