---
- name: Transfer file from SFTP to Windows
  hosts: 10.10.5.183
  gather_facts: yes

  tasks:
    - name: Copy file from SFTP to Windows
      win_copy:
        src: "sftp://kap-user@10.10.5.76/kap-user/test"  # Adjust the source path
        dest: "C:\\PrometheusExporter\\"
      delegate_to: 10.10.5.76
