---
- name: Enable WinRM
  hosts: 10.10.5.181  # Replace with the appropriate host/group name from your AWX inventory
  gather_facts: no
  tasks:
    - name: Set WinRM to allow Basic authentication
      win_shell: Set-Item -Path WSMan:\localhost\Service\Auth\Basic -Value $true
      become: yes

    - name: Set WinRM to allow unencrypted traffic
      win_shell: Set-Item -Path WSMan:\localhost\Service\AllowUnencrypted -Value $true
      become: yes

    - name: Restart WinRM service
      win_shell: Restart-Service WinRM
      become: yes
