---
- name: Transfer file from SFTP to Windows (Using win_copy)
  hosts: 10.10.5.183
  gather_facts: no

  tasks:
    - name: Copy file from SFTP to Windows
      win_copy:
        src: "/tmp/"
        dest: "C:\\PrometeusExporter\\test"
      delegate_to: localhost
