---
- hosts: 10.10.5.183
  tasks:
  - name: Ensure directory exists
    win_file:
      path: C:\PrometheusExporter
      state: directory

  - name: Copy files from FileZilla SFTP server to Windows 10
    win_copy:
      src: sftp://{{ sftp_username }}:{{ sftp_password }}@{{ sftp_host }}/{{ sftp_path }}/{{ file_name }}
      dest: C:\PrometheusExporter\{{ file_name }}

  vars:
    sftp_host: 10.10.5.76
    sftp_username: kap-user
    sftp_password: 123!@#
    sftp_path: /kap-user/
    file_name: test
