---
- name: Transfer files from SFTP to Windows
  hosts: 10.10.5.183 # Replace with your target host/group

  tasks:
    - name: Download files from SFTP
      win_shell: |
        # Your psftp or sftp command goes here to download files
          sftp kap-user@10.10.5.76:/kap-user/test/ /root/awx/

      args:
        executable: bash.exe
      environment:
        PSFTP_PASS: "123!@#"  # Replace with your SFTP password

    - name: Copy files to Windows server
      win_copy:
        src: "sftp://kap-user@10.10.5.76/kap-user/test"
        dest: "C:\\PrometheusExporter\\"
