---
- hosts: 10.10.5.183
  tasks:
  - name: Copy files from  SFTP server to Windows 11
    win_file:
      src: sftp://kap-user:123!@#10.10.5.76/kap-user/test
      dest: C:\\PrometheusExporter
      state: copy

  vars:
    sftp_host: 10.10.5.183
    sftp_username: kap-user
    sftp_password: 123!@#
    sftp_path: /kap-user/
    file_name: test
