- name: transfer file from MinIO to Windows
  hosts: 10.10.5.183
  gather_facts: true

  tasks:
    - name: download file from MinIO
      community.general.aws_s3:
        bucket: security
        object: /mnt/data/security/SQLite/sqlite3.exe
        dest: //PrometheusExporter//
        aws_access_key: DW1v3EfdBLR0J1GVhdjC
        aws_secret_key: 5VytN79seVFxeYmAmwLlYUF4O0rp0Hlnex50GyTf
        mode: get
        overwrite: yes
