---
- name: Transfer file from SFTP to Windows
  hosts: 10.10.5.183
  gather_facts: no

  tasks:
    - name: Fetch file from SFTP server
      fetch:
        src: "sftp://inndata@10.10.5.76//home//inndata//test"
        dest: "/tmp/test"
        validate_certs: no

    - name: Copy file to Windows server
      win_copy:
        src: "/tmp/test"
        dest: "C:\\prometheusexporter\\testfile"
