---
- name: Transfer file from SFTP to Windows
  hosts: 10.10.5.183
  gather_facts: yes

  tasks:
    - name: Copy file from SFTP to Windows
      win_copy:
        src: "/kap-user/test"  # Adjust the source path
        dest: "C:\\PrometheusExporter\\test"
      delegate_to: localhost
