---
- name: Copy file from Linux to Windows
  hosts: 10.10.5.76
  gather_facts: yes

  tasks:
    - name: Copy file from Linux to Windows
      ansible.builtin.copy:
        src: /path/to/source/file.txt
        dest: C:\path\to\destination\file.txt
