---
- name: Transfer files from SFTP to Windows
  hosts: 10.10.5.183  # Replace with your target host/group

  tasks:
    - name: Download files from SFTP
      win_shell: |
        # Create a PowerShell script file to execute sftp command
        echo "sftp kap-user@10.10.5.76:/kap-user/test/ /root/awx/" > sftp_script.ps1
        # Execute the PowerShell script
        powershell.exe -File sftp_script.ps1
      args:
        executable: powershell.exe
      environment:
        PSFTP_PASS: "123!@#"  # Replace with your SFTP password

    - name: Copy files to Windows server
      win_copy:
        src: "C:\\Users\\Public\\Downloads"
        dest: "C:\\PrometheusExporter"
