---
- name: Transfer file from MinIO to Windows Server
  hosts: 10.10.5.183
  gather_facts: no

  tasks:
    - name: Download file from MinIO
      community.general.aws_s3:
        bucket: security
        object: /mnt/data/security/SQLite/sqlite3.exe
        dest: /tmp/sqlite3.exe
        aws_access_key: your_access_key
        aws_secret_key: your_secret_key
        mode: get
        overwrite: yes

    - name: Copy file to Windows Server
      win_copy:
        src: /tmp/sqlite3.exe
        dest: C:/PrometheusExporter/
