- name: Transfer file from SFTP to Windows
  hosts: 10.10.5.183
  gather_facts: no

  tasks:
    - name: Fetch file from SFTP server
      fetch:
        src: "/kap-user/test"  # Make sure this is the correct path on the SFTP server
        dest: "/tmp/test"
        flat: yes
        validate_certs: no
        fail_on_missing: yes
