---
- hosts: 10.10.5.182
  become: no
  environment:
    MINIO_ACCESS_KEY: "SfE6ufvGqkoifcgM62li"
    MINIO_SECRET_KEY: "gRJuFGMMgo3yr7iMPBWkxlpIkQK4JXrjcXRJjPxq"
  tasks:
   - name: Download file from Minio
     win_get_url:
       url: "https://10.10.5.81:9091/shinobi/Arc_11102023/Arc_11102023/Arc.exe"
       dest: C:\\Users\\
       validate_certs: no

