---
- name: Transfer file from SFTP to awx
  hosts: 10.10.5.75
  gather_facts: no

  tasks:
    - name: Copy file from SFTP to awx
      ansible.builtin.copy:
        src: "sftp://inndata@10.10.5.76/inndata/test"
        dest: "/tmp/"
        delegate_to: 10.10.5.76
