---
- name: Uninstall Windows Exporter
  hosts: 10.10.5.183  # Replace with the actual group of Windows hosts
  become: yes

  tasks:
    - name: Stop Windows Exporter Service
      win_service:
        name: windows_exporter
        state: stopped

    - name: Uninstall Windows Exporter
      win_shell: |
        # Add commands to uninstall the Windows Exporter here

    - name: Remove Windows Exporter Files
      win_shell: |
        # Add commands to remove any files or directories related to the Windows Exporter here
