---
- name: Copy Executables from Minio
  hosts: 10.10.5.181
  gather_facts: yes

  tasks:
    - name: Copy PowerShell script to Windows machine
      win_copy:
        src: "C:\Users\inndata-kap-001\minio\copy_from_minio.ps1" # Update this path to the actual location of your PowerShell script
        dest: "C:\Users\Public\copy_from_minio.ps1"
      become: no

    - name: Execute PowerShell script
      win_shell: powershell.exe -File C:\Users\Public\copy_from_minio.ps1
      become: no
