---
- name: Copy file from Minio to Windows
  hosts: 10.10.5.76  # Replace with the actual alias or IP of your Minio server
  gatherfacts: yes
  tasks:
    - name: Download file from Minio
      win_get_url:
        url: "http://10.10.5.76:9001/security/SQLite/sqlite3.exe"
        dest: "C:\\PrometheusExporter\\sqlite3.exe"
      delegate_to: 10.10.5.75

- name: Verify file copied
  hosts: 10.10.5.183  # Replace with the actual alias or IP of your Windows server
  tasks:
    - name: Check if file exists
      stat:
        path: "C:\\PrometheusExporter\\sqlite3.exe"
      register: file_check

    - name: Print result
      debug:
        msg: "File {{ 'does' if file_check.stat.exists else 'does not' }} exist"
