---
- name: Download files from MinIO
  hosts: 10.10.5.76
  gather_facts: false

  tasks:
    - name: Download files
      hosts: 10.10.5.183
      gather_facts: false
      tasks:
        - name: Download file from MinIO
          community.general.aws_s3:
            bucket: your_bucket_name
            object: /security/SQLite/sqlite3.exe
            dest: /mnt/data/security/SQLite
            aws_access_key: your_access_key
            aws_secret_key: your_secret_key
            mode: get
            overwrite: yes
