---
- name: Transfer files from SFTP to Windows
  hosts: 10.10.5.183

  tasks:
    - name: Fetch file from SFTP server
      fetch:
        src: "sftp://inndata@10.10.5.76/inndata/testfile.txt"
        dest: "/inndata/"
        flat: no
        validate_certs: yes
        fail_on_missing: no

    - name: Copy file to Windows destination
      win_copy:
        src: "/inndata/"
        dest: "C:\\PrometheusExporter\\"
        remote_src: yes
